config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "foods#index"

  resources :foods, except: :update
  resources :recipes, except: :update do
    member do
      put :toggle_public
    end
    resources :recipe_foods, only: [:index, :new, :create, :destroy]
  end
  get '/public_recipes', to: 'public_recipes#index', as: 'public_recipes'
  get '/general_shopping_list', to: 'shopping_list#index', as: 'general_shopping_list'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the user here. For example:
    #
    return unless user.present?

    can :read, :all
    return unless user.admin?

    can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :recipes, through: :recipe_foods
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  validates :name, presence: true
  validates :preparation_time, presence: true
  validates :cooking_time, presence: true
  validates :description, presence: true

  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :foods, through: :recipe_foods

  def change_public_status
    update(public: !public)
  end
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  validates :quantity, presence: true

  belongs_to :recipe
  belongs_to :food
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :validatable

  has_many :recipes
  has_many :foods
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  include DeviseWhitelist
end

app/controllers/concerns/devise_whitelist.rb
module DeviseWhitelist
  extend ActiveSupport::Concern

  included do
    before_action :configure_permitted_parameters, if: :devise_controller?
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
    @foods = current_user.foods
  end

  def new
    @food = Food.new
  end

  def create
    @food = current_user.foods.new(food_params)
    if @food.save
      redirect_to foods_url, notice: 'Food item was successfully created.'
    else
      flash.now[:alert] = 'Food item could not be created.'
      render :new
    end
  end

  def destroy
    @food = Food.find(params[:id])
    @food.destroy
    redirect_to foods_url, notice: 'Food item was successfully deleted.'
  end

  private

  # Define permitted parameters for creating a new food item
  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity)
  end
end

app/controllers/public_recipes_controller.rb
class PublicRecipesController < ApplicationController
  def index
    @public_recipes = Recipe.where(public: true).order(created_at: :desc)
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  before_action :set_recipe_food, only: [:destroy]

  def new
    @recipe = Recipe.find(params[:recipe_id])
    @foods = Food.all
    @recipe_food = @recipe.recipe_foods.new
  end

  def create
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = @recipe.recipe_foods.new(recipe_food_params)

    if @recipe.user == current_user && @recipe_food.save
      redirect_to @recipe, notice: 'Ingredient successfully added'
    else
      @foods = Food.all
      render :new, status: :unprocessable_entity, alert: 'Error occured whiles adding ingredient (Food) !!!'
    end
  end

  def destroy
    @recipe_food.destroy
    redirect_to recipe_url, notice: 'Recipe food was deleted !!!'
  end

  private

  def set_recipe_food
    @recipe_food = RecipeFood.find(params[:id])
  end

  def recipe_food_params
    params.require(:recipe_food).permit(:quantity, :recipe_id, :food_id)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = current_user.recipes.includes(:user) if user_signed_in?
  end

  def show
    @recipe = Recipe.find(params[:id])
    @recipe_foods = @recipe.recipe_foods.includes(:food)
  end

  def new
    @recipe = current_user.recipes.build
  end

  def create
    @recipe = current_user.recipes.build(recipe_params)

    if @recipe.save
      redirect_to recipes_path, notice: 'New Recipe saved !!!.'
    else
      flash[:alert] = 'Failed to create recipe. Please check the form for errors.'
      render :new
    end
  end

  def destroy
    @recipe = current_user.recipes.find(params[:id])
    @recipe.destroy
    redirect_to recipes_path, notice: 'Recipe deleted successfully.'
  end

  def toggle_public
    @recipe = Recipe.find(params[:id])
    @recipe.change_public_status
    redirect_to @recipe, notice: 'Recipe status has changed.'
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :public, :description)
  end
end

app/controllers/shopping_list_controller.rb
class ShoppingListController < ApplicationController
  before_action :authenticate_user!

  def index
    @foods = Food.where.not(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index; end

  def show; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/public_recipes_helper.rb
module PublicRecipesHelper
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/shopping_list_helper.rb
module ShoppingListHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/foods/index.html.erb
<h1 class="title is-flex is-justify-content-center">List of Food</h1>

<div class="container" style="width: 60%;">
  <div class="container is-flex is-justify-content-end mb-4">
    <%= link_to "Add Food", new_food_path, class: "button is-info" %>
  </div>
  <div class="is-flex mt-4 mb-4">
    <table class="table is-hoverable is-fullwidth">
      <thead>
        <tr>
          <th class="has-text-dark-light">Food</th>
          <th class="has-text-dark-light">Measuring Unit</th>
          <th class="has-text-dark-light">Unit Price</th>
          <th class="has-text-dark-light">Action</th>
        </tr>
      </thead>
      <tbody>
        <% @foods.each do |food| %>
          <tr>
            <td> <%= food.name %></td>
            <td> <%= food.measurement_unit %></td>
            <td> $ <%= food.price %></td>
            <td><%= button_to 'Delete', food_path(food.id), method: :delete, class: "button has-background-danger-light has-text-danger is-small" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/foods/new.html.erb
<h1 class="title is-flex is-justify-content-center">Add New Food</h1>

<div class="container" style="width: 50%;">
  <%= form_with model: @food, url: foods_path, method: :post, local: true do |form| %>
    <div class="mb-3">
      <%= form.label :name, class: "label" %>
      <%= form.text_field :name, class: "input" %>
    </div>

    <div class="mb-3">
      <%= form.label :measurement_unit, class: "label" %>
      <%= form.text_field :measurement_unit, class: "input" %>
    </div>

    <div class="mb-3">
      <%= form.label :price, class: "label" %>
      <%= form.number_field :price, class: "input", step: 0.01 %>
    </div>

    <div class="mb-3">
      <%= form.label :quantity, class: "label" %>
      <%= form.number_field :quantity, class: "input", step: 0.01 %>
    </div>

    <div>
      <%= form.submit class: "button is-info" %>
    </div>
  <% end %>
</div>

app/views/foods/show.html.erb
<h1>Foods#show</h1>
<p>Find me in app/views/foods/show.html.erb</p>

app/views/public_recipes/index.html.erb
<h1 class="title is-flex is-justify-content-center">List of Public Recipes</h1>

<div class="container" style="width: 50%;">
  <% @public_recipes.each do |public_recipe| %>   
    <div class="is-flex mt-4 mb-4 column has-background-light radius-all">
      <div>
        <%= link_to public_recipe.name, recipe_path(public_recipe), class: "title is-5 has-text-grey is-info-dark" %>
        <p class="mt-3">By: <%= public_recipe.user.name %></p>
      </div>
      <div class="ml-5">
        <p>Total food items: <%= public_recipe.foods.count %></p>
        <p>Total price: <%= number_to_currency(public_recipe.foods.sum(:price))%></p>
      </div>
    </div>
  <% end %>
</div>

app/views/recipe_foods/new.html.erb
<h1 class="title is-flex is-justify-content-center">Add Ingredient to <%= @recipe.name%></h1>

<div class="container" style="width: 50%;">
 
  <% if flash[:error].present? %>
    <div class="subtitle has-text-danger-dark has-background-danger-light">
      <%= flash[:error] %>
    </div>
  <% end %>

  <%= form_with scope: :recipe_food, url:  recipe_recipe_foods_path do |form| %>
    <div class="mb-3">
      <%= form.label :food_id, "Food", class: "label" %>
      <%= form.collection_select :food_id, @foods, :id, :name, { prompt: "Select food item" }, class: "input" %>
    </div>

    <div class="mb-3">
      <%= form.label :quantity, "Quantity", class: "label" %>
      <%= form.number_field :quantity, class: "input" %>
    </div>

    <div class="d-flex justify-content-between gap-4">
      <%= form.submit "Add Ingredient", class: "button is-info is-light" %>
      <%= link_to "Cancel", recipe_path(@recipe), class: "button is-secondary" %>
    </div>
  <% end %>
</div>

app/views/recipes/index.html.erb
<h1 class="title is-flex is-justify-content-center">List of Recipes</h1>

<div class="container" style="width: 60%;">
  <div class="container is-flex is-justify-content-end mb-4">
    <%= link_to "Add Recipe", new_recipe_path, class: "button is-info" %>
  </div>

  <% @recipes.each do |recipe| %>   
    <div class="is-flex mt-4 mb-4 column has-background-light radius-all">
      <div>
        <%= link_to recipe.name, recipe_path(recipe), class: "title is-5 has-text-grey is-info-dark" %>
        <% if recipe.user == current_user %>
          <%= button_to 'Remove', recipe, method: :delete, data: { confirm: 'Are you sure you want to delete this recipe?' }, class: 'button has-text-danger-dark has-background-danger-light mt-5' %>
        <% end %>
      </div>
      <div class="ml-5">
        <p class="is-5 has-text-grey"> <%= recipe.description %></p>
      </div>
    </div>
  <% end %>
</div>

app/views/recipes/new.html.erb
<h1 class="title is-flex is-justify-content-center">New Recipe</h1>

<div class="container" style="width: 50%;">
  <%= form_with model: @recipe, url: recipes_path, method: :post, local: true do |form| %>
    <div class="mb-3">
      <%= form.label :name, class: "label" %>
      <%= form.text_field :name, class: "input" %>
    </div>

    <div class="mb-3">
      <%= form.label :preparation_time,"Preparation Time (hours)", class: "label" %>
      <%= form.number_field :preparation_time, class: "input", step: 0.01 %>
    </div>

    <div class="mb-3">
      <%= form.label :cooking_time, "Cooking Time (hours)", class: "label" %>
      <%= form.number_field :cooking_time, class: "input", step: 0.01 %>
    </div>

    <div class="mb-3">
      <%= form.label :description, class: "label" %>
      <%= form.text_area :description, class: "input" %>
    </div>

    <div class="mb-3">
      <%= form.label :public, class: "label" %>
      <%= form.label :public, "Yes" %>
      <%= form.radio_button :public, true, class: "mr-4" %>
      <%= form.label :public, "No" %>
      <%= form.radio_button :public, false %>
    </div>

    <div>
      <%= form.submit "Create Recipe", class: "button is-info" %>
    </div>
  <% end %>
</div>

app/views/recipes/show.html.erb
<h1 class="title is-flex is-justify-content-center"><%= @recipe.name%></h1>

<div class="container" style="width: 60%;">
  <div class="is-flex is-justify-content-space-between">
    <p class="my-3"><strong>Preparation time :</strong> <%= @recipe.preparation_time %> hours</p>
  <div class="is-flex is-justify-content-center is-align-items-center">
  <div class="mr-3">Public :</div>

  <%= form_with model: @recipe, url: toggle_public_recipe_path(@recipe), method: :put, local: true do |form| %>
    <div class="buttons has-addons">
      <%= form.submit 'Yes', class: (@recipe.public == true ? 'button is-small is-dark is-light' : 'button is-small') %>
      <%= form.submit 'No', class: (@recipe.public == false ? 'button is-small is-dark is-light' : 'button is-small') %>
    </div>
  <% end %>

  </div>
  </div>
  <p class="my-3"><strong>Cooking time :</strong> <%= @recipe.cooking_time %> hours</p>
  <p class="my-3"><strong>Steps go here ...</p>
  <div class="is-flex is-justify-content-space-between mt-3">
    <%= link_to 'Generate Shopping List', general_shopping_list_path, class: "button is-info is-light" %>
    <% if @recipe.user == current_user %>
      <%= link_to 'Add Ingredient',new_recipe_recipe_food_path(@recipe), class: "button is-warning is-light" %>
    <% end %>
  </div>
  <hr>

  <div class="is-flex mt-4 mb-4">
    <table class="table is-hoverable is-fullwidth">
      <thead>
        <tr>
          <th>Food</th>
          <th>Measuring Unit</th>
          <th>Value</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        <% @recipe.recipe_foods.each do |recipe_food| %>
          <tr class="has-text-weight-normal">
            <td> <%= recipe_food.food.name %></td>
            <td> <%= recipe_food.food.measurement_unit %></td>
            <td> $ <%= recipe_food.food.price * recipe_food.quantity %></td>
            <td class="is-flex">
              <%= button_to 'Modify',"", class: "button has-background-primary-light has-text-primary is-small p-1" %>
              <%= button_to 'Remove', recipe_recipe_food_path(@recipe, recipe_food), method: :delete, data: { confirm: 'Are you sure you want to delete this food?' }, class: "button has-background-danger-light has-text-danger-dark is-small ml-3 p-1" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/shopping_list/index.html.erb
<h1 class="title is-flex is-justify-content-center">Missing Food Items</h1>

<div class="container" style="width: 60%;">
  <div class="is-flex is-justify-content-space-between">
    <h1><strong>Amount of food items to buy : <%= @foods.count %></strong></h1>
    <h1><strong>Total value of food needed : <%= number_to_currency(@foods.sum(&:price)) %> </strong></h1>
  </div>
  <div class="is-flex mt-4 mb-4">
    <table class="table is-hoverable is-fullwidth">
      <thead>
        <tr>
          <th class="has-text-dark-light">Food</th>
          <th class="has-text-dark-light">Quantity</th>
          <th class="has-text-dark-light">Unit Price</th>
        </tr>
      </thead>
      <tbody>
        <% @foods.each do |food| %>
          <tr>
            <td> <%= food.name %></td>
            <td> <%= food.quantity %></td>
            <td> $ <%= food.price %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>